app/models.py
from app import db


class Gallery(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(200), nullable=False)
    content = db.Column(db.Text, nullable=False)
    create_date = db.Column(db.DateTime(), nullable=False)


class Comment(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    gall_id = db.Column(db.Integer, db.ForeignKey(
        'gallery.id', ondelete='CASCADE'))
    gall = db.relationship('Gallery', backref=db.backref('comment_set'))
    content = db.Column(db.Text, nullable=False)
    create_date = db.Column(db.DateTime(), nullable=False)


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(40), unique=True, nullable=False)
    password = db.Column(db.String(40), nullable=False)
    email = db.Column(db.String(40), unique=True, nullable=False)

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, PasswordField, EmailField
from wtforms.validators import DataRequired, Length, EqualTo, Email


class GalleryForm(FlaskForm):
    title = StringField('제목', validators=[DataRequired()])
    content = TextAreaField('내용', validators=[DataRequired()])


class UserCreateForm(FlaskForm):
    username = StringField('사용자이름', validators=[
                           DataRequired(), Length(min=3, max=25)])
    passwordOne = PasswordField(
        '비밀번호', validators=[DataRequired(), EqualTo('passwordTwo', '비밀번호가 일치하지 않습니다')])
    passwordTwo = PasswordField('비밀번호확인', validators=[DataRequired()])
    email = EmailField('Email', validators=[DataRequired(), Email()])


class UserLoginForm(FlaskForm):
    username = StringField('사용자이름', validators=[
                           DataRequired(), Length(min=3, max=25)])
    password = PasswordField('비밀번호', validators=[DataRequired()])

app/__init__.py
from flask import Flask
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy

import config

db = SQLAlchemy()
migrate = Migrate()


def create_app():
    app = Flask(__name__)
    app.config.from_object(config)

    # ORM
    db.init_app(app)
    migrate.init_app(app, db)
    from . import models

    # blueprint
    from .views import main_views, gall_views, comment_views, auth_views
    app.register_blueprint(main_views.bp)
    app.register_blueprint(gall_views.bp)
    app.register_blueprint(comment_views.bp)
    app.register_blueprint(auth_views.bp)

    return app

app/views/auth_views.py
from flask import Blueprint, url_for, render_template, flash, request, session, g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect

from app import db
from app.forms import UserCreateForm, UserLoginForm
from app.models import User

bp = Blueprint('auth', __name__, url_prefix='/auth')


@bp.route('/signup/', methods=('GET', 'POST'))
def signup():
    form = UserCreateForm()
    if request.method == 'POST' and form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            user = User(username=form.username.data,
                        password=generate_password_hash(form.passwordOne.data),
                        email=form.email.data)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('main.index'))
        else:
            flash('이미 존재하는 사용자입니다.')
    return render_template('auth/signup.html', form=form)


@bp.route('/login/', methods=('GET', 'POST'))
def login():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            error = "존재하지 않는 사람입니다."
        elif not check_password_hash(user.password, form.password.data):
            error = "비밀번호가 올바르지 않습니다."
        if error is None:
            session.clear()
            session['user_id'] = user.id
            return redirect(url_for('main.index'))
        flash(error)
    return render_template('auth/login.html', form=form)


@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get(user_id)


@bp.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for('main.index'))

app/views/coment_views.py
from datetime import datetime

from flask import Blueprint, url_for, request
from werkzeug.utils import redirect

from app import db
from app.models import Gallery

bp = Blueprint('coment', __name__, url_prefix='/coment')


@bp.route('/create/<int:id>', methods=('POST',))
def create(id):
    gall = Gallery.query.get_or_404(id)
    content = request.form("content")
    coment

app/views/comment_views.py
from datetime import datetime

from flask import Blueprint, url_for, request
from werkzeug.utils import redirect

from app import db
from app.models import Gallery, Comment

bp = Blueprint('comment', __name__, url_prefix='/comment')


@bp.route('/create/<int:id>', methods=('POST',))
def create(id):
    gall = Gallery.query.get_or_404(id)
    content = request.form["content"]
    comment = Comment(content=content, create_date=datetime.now())
    gall.comment_set.append(comment)
    db.session.commit()
    return redirect(url_for('gallery.detail', id=id))

app/views/gall_views.py
from datetime import datetime
from flask import Blueprint, render_template, request, url_for
from werkzeug.utils import redirect
from app import db
from app.models import Gallery
from app.forms import GalleryForm

bp = Blueprint('gallery', __name__, url_prefix='/gallery')


@bp.route('/list/')
def _list():
    gall_list = Gallery.query.order_by(Gallery.create_date.desc())
    return render_template('gallery/gall_list.html', gall_list=gall_list)


@bp.route('/detail/<int:id>/')
def detail(id):
    gallery = Gallery.query.get_or_404(id)
    return render_template('gallery/gall_content_detail.html', gallery=gallery)


@bp.route('/create/', methods=('GET', 'POST'))
def create():
    form = GalleryForm()
    if request.method == 'POST' and form.validate_on_submit():
        gallery = Gallery(title=form.title.data,
                          content=form.content.data, create_date=datetime.now())
        db.session.add(gallery)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('gallery/gall_form.html', form=form)

app/views/main_views.py
from flask import Blueprint, url_for
from werkzeug.utils import redirect

from app.models import Gallery

bp = Blueprint('main', __name__, url_prefix='/')


@bp.route('/')
def index():
    return redirect(url_for('gallery._list'))

app/templates/base.html
<!DOCTYPE html>
<html lang="ko">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
    <title>안녕, 게시판!</title>
</head>

<body>
    <!-- 네비게이션바 -->
    {% include "navbar.html" %}
    <!-- 기본 템플릿 안에 삽입될 내용 Start -->
    {% block content %}
    {% endblock %}
    <!-- 기본 템플릿 안에 삽입될 내용 End -->
    <!-- Bootstrap JS -->
    <script src="{{ url_for('static', filename='bootstrap.min.js') }}"></script>
</body>

</html>

app/templates/form_errors.html
<!-- 필드오류 -->
{% if form.errors %}
<div class="alert alert-danger" role="alert">
    {% for field, errors in form.errors.items() %}
    <strong>{{ form[field].label }}</strong>
    <ul>
        {% for error in errors %}
        <li>{{ error }}</li>
        {% endfor %}
    </ul>
    {% endfor %}
</div>
{% endif %}
<!--flash 오류-->
{% for message in get_flashed_messages() %}
<div class="alert alert-danger" role="alert">
    {{ message }}
</div>
{% endfor %}

app/templates/gallery/gall_content_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <!--글 본문-->
    <h2 class="border-bottom py-2">{{ gallery.title }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ gallery.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge be-light text-dark p-2">
                    {{ gallery.create_date}}
                </div>
            </div>
        </div>
    </div>

    <!--덧글 목록-->
    <h5 class="border-bottom my-3 py-2">{{gallery.comment_set|length}}개의 덧글이 있습니다.</h5>
    {% for comment in gallery.comment_set %}
    <div class="card my-2">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ comment.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge be-light text-dark p-1">
                    {{comment.create_date}}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <!--덧글 등록-->
    <form action="{{url_for('comment.create',id=gallery.id)}}" method="post" class="mb-3">
        <div class="mb-3">
            <textarea name="content" id="content" class="form-control" rows="5"></textarea>
        </div>
        <input type="submit" value="덧글작성">
    </form>
</div>
{% endblock %}

app/templates/gallery/gall_form.html
{% extends 'base.html' %}
{% block content %}
<!--글 작성-->
<div class="container">
    <h5 class="my-3 border-bottom pb-2">글 작성하기</h5>
    <form method="post" class="my-3">
        {{ form.csrf_token }}
        {{ form.title.label }}
        {{ form.title(class="form-control")}}

        {{ form.content.label }}
        {{ form.content(class="form-control")}}
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
    <form method="post" class="post-form my-3">
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field, errors in form.errors.items() %}
            <strong>{{ form[field].label }}</strong>
            <ul>
                {% for error in errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="form-group">
        </div>
        {% endblock %}

app/templates/gallery/gall_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
            <tr class="table-dark">
                <th>번호</th>
                <th>제목</th>
                <th>작성일시</th>
            </tr>
        </thead>
        <tbody>
            {% if gall_list %}
            {% for gallery in gall_list %}
            <tr>
                <td>{{ loop.index }}</td>
                <td>
                    <a href="{{ url_for('gallery.detail',id=gallery.id)}}">{{ gallery.title}}</a>
                </td>
                <td>{{ gallery.create_date }}</td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="3">글이 없습니다</td>
            </tr>
            {% endif %}
        </tbody>
    </table>
    <a href="{{ url_for('gallery.create')}}" class="btn btn-primary">글 작성하기</a>
</div>
{% endblock %}

app/templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('main.index') }}">Gallery</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            {% if g.user %}
            <ul class="navbar-nav">
                <li class="nav-item ">
                    <a class="nav-link" href="{{ url_for('auth.logout') }}">{{ g.user.username }} (로그아웃)</a>
                </li>
            </ul>
            {% else %}
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.signup') }}">계정생성</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.login') }}">로그인</a>
                </li>
            </ul>
            {% endif %}
        </div>
    </div>
</nav>